version: '3.5'

services:
  # === LOGS ===
  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.2.0

    # load config stored in repository
    # uncomment when needed
    # volumes:
    #   - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticserach/config/elasticsearch.yml:ro 
    environment:
      - discovery.type=single-node #run elasticsearch as a standalone server, not a node
    ulimits:
      memlock: #set unlimited memory for processes. Required by elasticsearch
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    volumes:
    # load config shored in repository
    # uncomment when needed
    #  - ./configs/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro

    # Folder with Logstash pipeline configs
      - ./configs/logstash/:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 9600:9600
    environments:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0

    #load config stored in repository
    # uncomment when needed
    # volumes:
    #   - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro 
    ports:
      - 5601:5601